/*	Ryuzine Localization Add-On
	Version 1.0
	
	This is a file to aid translation contributors
	
	DO NOT EDIT THIS FILE!  EDIT FILES IN /language
	
	It includes the strings for dynamically created text 
	in alert(), confirm(), and prompt() dialogs which
	cannot be parsed out of the document elements.
*/

RYU.addon.localize.modals.webapp = [
"Name",
"Version",
"Author",
"Website",
"License",
"Ryuzine™ is a javascript application designed for publishing content to the web and mobile devices in a familiar magazine-style format.",
"Publishing Kit available at",
"Ryuzine was created by K.M. Hansen, original code ©2011-2015 All Rights Reserved.",
"Read the license and a list of project contributors:",
"LICENSE FILE",
"CONTRIBUTORS",
"Ryuzine and the Ryuzine logos are trademarks of K.M. Hansen and Ryu Maru. All rights reserved. The names of other companies, products, services and content distributed via the Ryuzine publishing platform are the property of their respective owners.",
"Add Bookmark for Page",
"Confirm Bookmark Deletion for Page",
"Bookmark list is empty",
"Error: Configuration file could not be found!",
"App Error: Loading configuration variables failed.",
"This item is already on your reading list.",
"Add to Reading List?",
"Remove from Reading List?",
"App Error: can not find item in reading list",
"Found",
"matches",
"Reading List is empty.",
"Go Back to Rack",
"My Reading List",
"Hiding dialogs is being overidden, go to OPTIONS > SHOW ALL DIALOGS and turn it OFF to allow hiding",
"DELETE ENTIRE READING LIST? (Warning: This cannot be undone!)"
];