/*	Ryuzine WRITER Localization Add-On
	Version 1.0
	
	This is a file to aid translation contributors
	
	DO NOT EDIT THIS FILE!  EDIT FILES IN /language
	
	It includes the strings for dynamically created text 
	in alert(), confirm(), and prompt() dialogs which
	cannot be parsed out of the document elements.
*/

RYU.addon.localize.modals.webapp = [
"Name",
"Version",
"Author",
"Website",
"License",
"Ryuzine™ is a javascript application designed for publishing content to the web and mobile devices in a familiar magazine-style format.",
"Publishing Kit available at",
"Ryuzine was created by K.M. Hansen, original code ©2011-2015 All Rights Reserved.",
"Read the license and a list of project contributors:",
"LICENSE FILE",
"CONTRIBUTORS",
"Ryuzine and the Ryuzine logos are trademarks of K.M. Hansen and Ryu Maru. All rights reserved. The names of other companies, products, services and content distributed via the Ryuzine publishing platform are the property of their respective owners.",
"Error: configuration file missing!",
"Hiding dialogs is being overidden, go to OPTIONS > SHOW ALL DIALOGS and turn it OFF to allow hiding",
"Ryuzine Writer will now attempt to reload and reset the UI.",
"Setting takes effect after reloading Ryuzine Writer.",
"Your In-Page Styles will be added to the CSS Export Box and written into the page for testing. Before you publish you should export it to an external stylesheet.",
"Your In-Page Styles will be written into the page for testing. Before publishing you should copy them into an external stylesheet.",
"You appear to be using In-Page Styles. Unless you check PRESERVE IN-PAGE STYLES in the Output Options or you copy and paste the CSS code into your external stylesheet they will not be used.",
"Configuration File is set to TEST but there is no configuration to test!",
"A default one will automatically be built for you.",
"Using TEST CONFIGURATION FILE",
"Before final export you should switch the Output Options selection for the configuration file to either DEFAULT or a CUSTOM external file.",
"Using an in-page configuration file is not recommended.",
"Configuration File was not defined, using default!",
"Error: This is a Ryuzine Rack Newsstand.  Editing this file is only recommended for advanced authors.",
"Error: File could not be converted",
"This file appears to be an InDesign > Export for Dreamweaver file. It will be converted to Ryuzine format. You should save from the Editor immediately and in the future import the new file instead of this one.",
"Numbers Only!",
"ERROR: Custom Issue-Specific stylesheet filename missing, using default.",
"Error: Unknown list.",
"Delete Entry",
"You must enter a catalog file name",
"This is not a valid catalog file.",
"Change takes effect after reloading Ryuzine Writer",
"Error: Unknown file type!",
"Some document Output Options are not compatible with this setting. The Output Options will now be adjusted and the Ryuzine File regenerated so it will work",
"HTML Export Box is empty!  Go to Editor, Build file, and then Package.",
"Configuration Export Box is empty!  Using Default file.",
"CSS Export Box is empty!  Using default thisissue.css file.",
"Data Export Box is empty!  Build a Catalog file or change the Package option.",
"Package type unknown!",
"You cannot deselect BOTH Ryuzine and RyuzineRack!",
"No pages are selected!",
"pages",
"Are you sure you want to delete",
"This cannot be undone!",
"Heading",
"Put your page content here",
"insert count set at zero, no action taken",
"How many pages would you like to add?"
];